// Firmware_Teensy_AiO-New-Dawn is copyright 2025 by the AOG Group
// Firmware_Teensy_AiO-New-Dawn is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// Firmware_Teensy_AiO-New-Dawn is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with Firmware_Teensy_AiO-New-Dawn. If not, see <https://www.gnu.org/licenses/>.

// TouchFriendlyCANSnifferPage.h - Simple CAN Sniffer web page (Serial Monitor style)

#ifndef TOUCH_FRIENDLY_CAN_SNIFFER_PAGE_H
#define TOUCH_FRIENDLY_CAN_SNIFFER_PAGE_H

namespace CANSnifferPage {

    const char PAGE[] PROGMEM =
        "<!DOCTYPE html>"
        "<html lang='en'>"
        "<head>"
        "<meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<title>CAN Sniffer - AiO v26</title>"
        "<style>"
        "* { box-sizing: border-box; margin: 0; padding: 0; }"
        "body {"
        "  font-family: monospace;"
        "  background: #1a1a1a;"
        "  color: #00ff00;"
        "  padding: 10px;"
        "}"
        ".sniffer-container { max-width: 100%; margin: 0 auto; }"
        ".controls-row {"
        "  display: flex;"
        "  flex-wrap: wrap;"
        "  gap: 10px;"
        "  padding: 10px 0;"
        "  align-items: center;"
        "}"
        ".toggle-label {"
        "  display: flex;"
        "  align-items: center;"
        "  gap: 8px;"
        "  font-size: 14px;"
        "}"
        ".toggle-label input[type='checkbox'] {"
        "  width: 20px;"
        "  height: 20px;"
        "  cursor: pointer;"
        "}"
        "select, button {"
        "  background: #333;"
        "  color: #00ff00;"
        "  border: 1px solid #00ff00;"
        "  padding: 8px 12px;"
        "  font-family: monospace;"
        "  font-size: 14px;"
        "  cursor: pointer;"
        "  border-radius: 4px;"
        "}"
        "button:hover, select:hover { background: #444; }"
        "button:active { background: #555; }"
        ".stats {"
        "  padding: 5px 0;"
        "  font-size: 12px;"
        "  color: #888;"
        "}"
        ".can-log {"
        "  background: #000;"
        "  color: #00ff00;"
        "  border: 1px solid #444;"
        "  padding: 10px;"
        "  font-family: 'Courier New', monospace;"
        "  font-size: 12px;"
        "  line-height: 1.4;"
        "  min-height: 300px;"
        "  max-height: 60vh;"
        "  overflow-y: auto;"
        "  white-space: pre-wrap;"
        "  word-wrap: break-word;"
        "  border-radius: 4px;"
        "}"
        ".status-offline { color: #ff4444; }"
        ".status-online { color: #00ff00; }"
        ".buffer-warning { color: #ffaa00; }"
        "</style>"
        "</head>"
        "<body>"
        "<div class='sniffer-container'>"
        "<h2>CAN Bus Sniffer</h2>"

        "<div class='controls-row'>"
        "<label class='toggle-label'>"
        "<input type='checkbox' id='snifferEnable' onchange='toggleSniffer()'>"
        "<span id='enableStatus' class='status-offline'>OFF</span>"
        "</label>"

        "<select id='busSelect' onchange='selectBus()'>"
        "<option value='1'>CAN1</option>"
        "<option value='2'>CAN2</option>"
        "<option value='3'>CAN3</option>"
        "</select>"

        "<button onclick='clearLog()'>Clear</button>"
        "</div>"

        "<div class='stats'>"
        "Messages: <span id='msgCount'>0</span> | "
        "Buffer: <span id='bufferUsage'>0%</span> | "
        "Polling: 200ms"
        "</div>"

        "<pre id='can-log' class='can-log'>CAN Sniffer disabled. Enable to start logging.</pre>"
        "</div>"

        "<script>"
        "let pollInterval = null;"
        "let isEnabled = false;"

        "function toggleSniffer() {"
        "  const checkbox = document.getElementById('snifferEnable');"
        "  const status = document.getElementById('enableStatus');"
        "  isEnabled = checkbox.checked;"
        "  "
        "  fetch('/cansniffer/enable?state=' + (isEnabled ? '1' : '0'), {method: 'POST'})"
        "    .then(() => {"
        "      status.textContent = isEnabled ? 'ON' : 'OFF';"
        "      status.className = isEnabled ? 'status-online' : 'status-offline';"
        "      "
        "      if (isEnabled && !pollInterval) {"
        "        pollInterval = setInterval(refreshLog, 200);"
        "        refreshLog();  // Immediate refresh"
        "      } else if (!isEnabled) {"
        "        clearInterval(pollInterval);"
        "        pollInterval = null;"
        "        document.getElementById('can-log').textContent = 'CAN Sniffer disabled.';"
        "      }"
        "    });"
        "}"

        "function refreshLog() {"
        "  if (!isEnabled) return;"
        "  "
        "  Promise.all(["
        "    fetch('/cansniffer/log').then(r => r.text()),"
        "    fetch('/cansniffer/stats').then(r => r.json())"
        "  ]).then(([logText, stats]) => {"
        "    const logEl = document.getElementById('can-log');"
        "    const wasAtBottom = logEl.scrollHeight - logEl.scrollTop <= logEl.clientHeight + 50;"
        "    "
        "    logEl.textContent = logText || 'No messages yet...';"
        "    "
        "    if (wasAtBottom) {"
        "      logEl.scrollTop = logEl.scrollHeight;"
        "    }"
        "    "
        "    document.getElementById('msgCount').textContent = stats.count || 0;"
        "    const usage = stats.buffer || 0;"
        "    const bufEl = document.getElementById('bufferUsage');"
        "    bufEl.textContent = usage + '%';"
        "    bufEl.className = usage > 80 ? 'buffer-warning' : '';"
        "  }).catch(err => {"
        "    console.error('Refresh error:', err);"
        "  });"
        "}"

        "function selectBus() {"
        "  const bus = document.getElementById('busSelect').value;"
        "  fetch('/cansniffer/bus?num=' + bus, {method: 'POST'})"
        "    .then(() => {"
        "      if (isEnabled) refreshLog();"
        "    });"
        "}"

        "function clearLog() {"
        "  fetch('/cansniffer/clear', {method: 'POST'})"
        "    .then(() => {"
        "      document.getElementById('can-log').textContent = 'Cleared.';"
        "      if (isEnabled) refreshLog();"
        "    });"
        "}"

        "// Restore previous state on page load"
        "window.onload = function() {"
        "  fetch('/cansniffer/status')"
        "    .then(r => r.json())"
        "    .then(data => {"
        "      if (data.enabled) {"
        "        document.getElementById('snifferEnable').checked = true;"
        "        document.getElementById('enableStatus').textContent = 'ON';"
        "        document.getElementById('enableStatus').className = 'status-online';"
        "        isEnabled = true;"
        "        pollInterval = setInterval(refreshLog, 200);"
        "        refreshLog();"
        "      }"
        "      if (data.bus) {"
        "        document.getElementById('busSelect').value = data.bus;"
        "      }"
        "    });"
        "};"
        "</script>"
        "</body>"
        "</html>";
}

#endif // TOUCH_FRIENDLY_CAN_SNIFFER_PAGE_H
